### ISSUE TITLE
Create shout module

### ISSUE THREAD

**Issue by jbshep** [jbshep/gh-test#1]
Create a `shout` function in a module named `shout`. 
If we pass a string to `shout`, it should return an uppercase version of the string followed by a silly number of exclamation marks.

**Comment by bvcsdemo** [comment]
Am I supposed to import this function and module into `main.py`?

**Comment by jbshep** [comment]
Yes.  That's a really idea.  You're a good employee, and you deserve a raise.  Unfortunately that's not my call.

**Comment by jbshep** [comment]
This was closed in PR #3.
